enableSodiumMenu = true
useBlockStateCulling = false
useCustomItemFrameRenderer = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingDepth = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
simplechunkloader = true
farmersdelight = true
yigd = true
iammusicplayer = true
createaddition = true
byg = true
create = true
milk = true
brewery = true
decorative_blocks = true
computercraft = true
another_furniture = true
create_crystal_clear = true
minecraft = true
